[package]
name = "exporter_proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
prometheus_exporter = "0.8.5"
regex = "1.7.1"
